receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  # export metrics data on 0.0.0.0:9999
  prometheus:
    endpoint: 0.0.0.0:9999
  # export logs to the Loki container otlp endpoint
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  # export traces to the Tempo container
  otlp/tempo:
    endpoint: tempo:5317
    tls:
      insecure: true
  # output to logs
  debug:
    verbosity: detailed

service:
  pipelines:
    # send logs to loki and debug exporters
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp/loki, debug ]
    # send metrics to prometheus and debug exporters
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus, debug ]
    # send traces to Tempo and debug exporter
    traces:
      receivers: [ otlp ]
      exporters: [ otlp/tempo, debug ]
