receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  # export metrics data on 0.0.0.0:9999
  prometheus:
    endpoint: 0.0.0.0:9999
  # export metrics to the Loki container otlp endpoint
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  # output to logs
  debug:
    verbosity: detailed

service:
  pipelines:
    # send logs to loki and debug exporters
    logs:
      receivers: [ otlp ]
      exporters: [ otlphttp/loki, debug ]
    # send metrics to prometheus and debug exporters
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus, debug ]
    # send traces to the debug exporter
    traces:
      receivers: [ otlp ]
      exporters: [ debug ]
